### ISSUE TITLE
kein epg mehr

### ISSUE THREAD

**Issue by di-le** [chriszero/epgd-plugin-tvsp#4]
Hallo,

hat sich etwas verändert ? Ich bekomme aktuell keine neuen EPG Daten, für keinen Sender mehr rein. Auf den ersten Blick konnte ich auch keine Auffälligkeiten in den Logfiles erkennen.

Vielen Dank für's prüfen.

**Comment by chriszero** [comment]
Ohne Log's kann ich nicht machen... Bitte nachreichen.

di-le <notifications@github.com> schrieb am So., 12. Mai 2019, 11:18:

**Comment by di-le** [comment]
Ich wollte nur fragen ob es ein generelles Problem gibt oder der Fehler nur bei mir Auftritt. Ich liefere nachher noch Logfiles.

**Comment by di-le** [comment]
Ich hab mir das nochmal genauer angeschaut und festgestellt das die Daten in der Datenbank landen aber nicht beim Client angekommen sind. Fehlermeldungen hatte ich keine aber nachdem ich den MySQL Server neu gestartet habe, funktioniert es jetzt wieder an den Clients.

Vielen Dank für den Repositorie und deine investierte Zeit.
